id: P8F7E6716
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA2CZ6618
  instance_id: http://purl.bdrc.io/resource/IE2CZ6618
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བཀའ་འགྱུར་ཀློག་སྐབས་དྲན་གསོར་བྲིས་པ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P2CZ6619
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    f8a108ec8bc94ad2a8f5c544b0f70d14:
      title: པོད ༡་བཀའ་འགྱུར་ཀློག་སྐབས་དྲན་གསོར་བྲིས་དེབ
      volume_number: 1
      base_file: UT2CZ6618_I2DB71080_0000.txt
      reference: http://purl.bdrc.io/resource/VL725BE79CC0F06BBF
      image_group: I2DB71080
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W2CZ6618
  - http://purl.bdrc.io/resource/MW2CZ6618
  ocr_software: Namsel
created_at: '2021-12-22T11:12:49.350414'
last_modified_at: '2021-12-22T11:12:49.350420'
